# 控制是否以及如何将依赖项添加到默认目录中
catalogMode: prefer

# 是否忽略向工作区根目录添加依赖时的警告提示
ignoreWorkspaceRootCheck: true

# npm 包注册表的基本 URL（包括尾部斜杠）
registry: https://registry.npmmirror.com

# 是否强制提升所有依赖
shamefullyHoist: true

# 在执行脚本时使用POSIX shell模拟器替代系统原生shell
shellEmulator: true

# 用于控制是否严格检查对等依赖（peer dependencies）的版本一致性。
# 当设置为 true 时，pnpm 会强制安装指定版本的对等依赖；
# 设置为 false 时，会忽略版本不一致的警告
strictPeerDependencies: false

# 当设置为“禁止降级”时，如果软件包的信任级别较之前的版本有所降低，pnpm 将无法安装
trustPolicy: no-downgrade

# 列出一个或多个 pnpm 应该允许安装的特定软件包或版本，即使这些软件包不满足信任策略要求。
trustPolicyExclude:
  - semver
  - chokidar
  - cached-factory
  - mermaid
  - '@oxc-resolver/binding-win32-x64-msvc'
  - '@oxc-resolver/binding-win32-arm64-msvc'
  - '@oxc-resolver/binding-linux-x64-gnu'
  - '@oxc-resolver/binding-linux-arm64-gnu'
  - '@oxc-resolver/binding-darwin-x64'
  - '@oxc-resolver/binding-darwin-arm64'

packages:
  - packages/*

catalogs:
  dev:
    '@lincy/unocss-base-config': ^2.6.2
    '@vitejs/plugin-vue': ^6.0.5
    '@vitejs/plugin-vue-jsx': ^5.1.5
    '@vue/compiler-sfc': ^3.5.30
    bumpp: ^11.0.1
    cross-env: ^10.1.0
    express-rate-limit: ^8.3.1
    lint-staged: ^16.4.0
    mockjs: ^1.1.0
    nodemon: ^3.1.14
    polyfill-library: ^4.8.0
    postcss: ^8.5.8
    sass-embedded: ^1.98.0
    simple-git-hooks: ^2.13.1
    tsup: ^8.5.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    unocss: ^66.6.7
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    unplugin-vue-macros: ^2.14.5
    vite: ^7.3.1
    vite-plugin-mock: ^3.0.2
    vite-plugin-pwa: ^1.2.0
    vue-tsc: ^3.2.6

  icons:
    '@iconify-json/mdi': ^1.2.3

  lint:
    '@lincy/eslint-config': ^6.5.2
    '@lincy/stylelint-config': ^2.2.2
    '@unocss/eslint-plugin': ^66.6.7
    eslint: ^10.0.3
    eslint-plugin-format: ^2.0.1
    stylelint: ^17.4.0

  node:
    compression: ^1.8.1
    cookie-parser: ^1.4.7
    express: ^5.2.1
    http-proxy-middleware: ^3.0.5
    lru-cache: ^11.2.7
    morgan: ^1.10.1
    request-ip: ^3.3.0
    serve-static: ^2.2.1

  prod:
    '@kangc/v-md-editor': ^2.3.18
    '@lincy/utils': ^0.7.3
    '@unhead/ssr': ^2.1.12
    '@unhead/vue': ^2.1.12
    '@vue/server-renderer': ^3.5.30
    '@vueuse/core': ^14.2.1
    axios: ^1.13.6
    element-plus: ^2.13.5
    js-cookie: ^3.0.5
    lodash: ^4.17.23
    md5: ^2.3.0
    pinia: ^3.0.4
    prismjs: ^1.30.0
    qs: ^6.15.0
    store2: ^2.14.4
    vue: ^3.5.30
    vue-content-loader: ^2.0.1
    vue-loading-overlay: ^6.0.6
    vue-router: ^5.0.3

  types:
    '@types/compression': ^1.8.1
    '@types/cookie-parser': ^1.4.10
    '@types/express': ^5.0.6
    '@types/js-cookie': ^3.0.6
    '@types/lodash': ^4.17.24
    '@types/md5': ^2.3.6
    '@types/morgan': ^1.9.10
    '@types/polyfill-library': ^3.108.4
    '@types/prismjs': ^1.26.6
    '@types/request-ip': ^0.0.41
    '@types/serve-static': ^2.2.0

onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - '@parcel/watcher'

peerDependencyRules:
  ignoreMissing:
    - rollup
    - esbuild
    - postcss
    - prettier
