/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('./components/a-input.vue')['default']
    AsideAccount: typeof import('./components/aside-account.vue')['default']
    AsideCategory: typeof import('./components/aside-category.vue')['default']
    AsideOther: typeof import('./components/aside-other.vue')['default']
    AsideTrending: typeof import('./components/aside-trending.vue')['default']
    BackendMenu: typeof import('./components/backend-menu.vue')['default']
    BackTop: typeof import('./components/back-top.vue')['default']
    BgPlum: typeof import('./components/bg-plum.vue')['default']
    ClientOnly: typeof import('./components/client-only.vue')['default']
    FrontendComment: typeof import('./components/frontend-comment.vue')['default']
    GlobalNavigation: typeof import('./components/global-navigation.vue')['default']
    ItemActions: typeof import('./components/item-actions.vue')['default']
    ReloadPrompt: typeof import('./components/reload-prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/sign-in.vue')['default']
    SignUp: typeof import('./components/sign-up.vue')['default']
    TopicsItem: typeof import('./components/topics-item.vue')['default']
    TopicsItemNone: typeof import('./components/topics-item-none.vue')['default']
  }
}

// For TSX support
declare global {
  const AInput: typeof import('./components/a-input.vue')['default']
  const AsideAccount: typeof import('./components/aside-account.vue')['default']
  const AsideCategory: typeof import('./components/aside-category.vue')['default']
  const AsideOther: typeof import('./components/aside-other.vue')['default']
  const AsideTrending: typeof import('./components/aside-trending.vue')['default']
  const BackendMenu: typeof import('./components/backend-menu.vue')['default']
  const BackTop: typeof import('./components/back-top.vue')['default']
  const BgPlum: typeof import('./components/bg-plum.vue')['default']
  const ClientOnly: typeof import('./components/client-only.vue')['default']
  const FrontendComment: typeof import('./components/frontend-comment.vue')['default']
  const GlobalNavigation: typeof import('./components/global-navigation.vue')['default']
  const ItemActions: typeof import('./components/item-actions.vue')['default']
  const ReloadPrompt: typeof import('./components/reload-prompt.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SignIn: typeof import('./components/sign-in.vue')['default']
  const SignUp: typeof import('./components/sign-up.vue')['default']
  const TopicsItem: typeof import('./components/topics-item.vue')['default']
  const TopicsItemNone: typeof import('./components/topics-item-none.vue')['default']
}