/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AInput: typeof import('./components/a-input.vue')['default']
    AsideAccount: typeof import('./components/aside-account.vue')['default']
    AsideCategory: typeof import('./components/aside-category.vue')['default']
    AsideOther: typeof import('./components/aside-other.vue')['default']
    AsideTrending: typeof import('./components/aside-trending.vue')['default']
    BackendMenu: typeof import('./components/backend-menu.vue')['default']
    BackTop: typeof import('./components/back-top.vue')['default']
    BgPlum: typeof import('./components/bg-plum.vue')['default']
    ClientOnly: typeof import('./components/client-only.vue')['default']
    FrontendComment: typeof import('./components/frontend-comment.vue')['default']
    GlobalNavigation: typeof import('./components/global-navigation.vue')['default']
    ItemActions: typeof import('./components/item-actions.vue')['default']
    ReloadPrompt: typeof import('./components/reload-prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/sign-in.vue')['default']
    SignUp: typeof import('./components/sign-up.vue')['default']
    TopicsItem: typeof import('./components/topics-item.vue')['default']
    TopicsItemNone: typeof import('./components/topics-item-none.vue')['default']
  }
}
